version: "3.1"

services:
  c_postgres_db:
    container_name: c_postgres_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=123456789
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_DB=test_db
      - POSTGRES_USER=ozgurhan
    volumes:
      - /Users/ozgurhanpolat/docker_practice/postgres/data:/var/lib/postgresql/data/pgdata

